#    Ajout d'une nouvelle route pour afficher "hello the world"
#hello_the_world:
#    path:     /hello-world
#    defaults: { _controller: BCPlatformBundle:Advert:index }
#On peut supprimer notre première route car celle de platform_home pointe dans le même direction
bye_the_world:
    path:    /bye-world
    defaults: { _controller: BCPlatformBundle:Advert:end }

bc_platform_home:
    path:    /platform
    defaults: { _controller: BCPlatformBundle:Advert:index}

bc_platform_view:
    path:    /advert/{id}
    defaults: { _controller: BCPlatformBundle:Advert:view}

bc_platform_view_slug:
    path:    /{year}/{slug}.{format}
    defaults: { _controller: BCPlatformBundle:Advert:viewSlug, format:    html }
#On rend le paramètre format facultatif en le mettant dans defaults
#On rajoute des contraintes dans les paramètres afin que $year n'accepte que des chiffres
    requirements:
      year:    \d{4}
      format: html|xml

bc_platform_add:
    path:    /add
    defaults: { _controller: BCPlatformBundle:Advert:add}



